Add Lift Inspector to D8  Module
acquia/acquia_lift pull request #252
Opened 2016-12-18 21:16 UTC by briancwald

I have my Lift Inspector from Demo Framework to go in Lift D8 module, including a number of reactors to make it work generically across all accounts.

## To use: 
- Go to lift config page, turn on Lift Inspector
- In the browser with Lift enabled, press "Ctrl + i"

## New features:
**- Added inspector as optional (off by default) feature that can be enabled and disabled from the Acquia Lift config page**
<img width="905" alt="screenshot 2016-12-18 16 08 55" src="https://cloud.githubusercontent.com/assets/776942/21296557/6138b18e-c53c-11e6-8f42-40e3d4e22754.png">

**- Style Inspector to closer match Lift sidebar styles**
<img width="966" alt="screenshot 2016-12-18 16 03 35" src="https://cloud.githubusercontent.com/assets/776942/21296570/a025dcc8-c53c-11e6-8e8a-e02c378e7582.png">

**Deep linking to segments, customer and current users tracking ID (note, must set the subdomain for lift profile manager in the settings page)**

## Fixes
- Better key mapping so that you can prompt the inspector from any browser.
- Callback on dialog load to lock the dialog from background scrolling when open

2016-12-20 09:47 UTC, nickveenhof commented
acquia_lift.settings:advanced.inspector_status missing schema,
    acquia_lift.settings:advanced.profile_manager_url missing schema in

So you need to adjust the config files :)

2017-01-06 14:03 UTC, nickveenhof requested changes

2017-01-06 14:03 UTC, nickveenhof commented on acquia_lift.module
> +  if ($lift_inspector) {
Better to set === TRUE if we are talking about a boolean. As PHP can be quite quirky sometimes when not strictly defined.

2017-01-06 14:03 UTC, nickveenhof commented on assets/lift_inspector/acquia_lift_inspector.css
> +
Remove double newlines

2017-01-06 14:03 UTC, nickveenhof commented on assets/lift_inspector/acquia_lift_inspector.js
> +      function show_inspector_modal() {
Let's make this camelcase, as good JS citizens

2017-01-06 14:03 UTC, nickveenhof commented on assets/lift_inspector/acquia_lift_inspector.js
> +        if (accountSubDomain) {
is the profile_manager_url always only a prefix?

2017-01-06 14:03 UTC, nickveenhof commented on assets/lift_inspector/acquia_lift_inspector.js
> +          '<div id="lift-inspector">' +
Can't we somehow load this in from somewhere else? html in JS is so ugly :(

2017-01-06 14:03 UTC, nickveenhof commented on assets/lift_inspector/acquia_lift_inspector.js
> +      $(document).keypress(function (e) {
Will this work in all browsers?

2017-01-06 14:03 UTC, nickveenhof commented on src/Form/AdminSettingsForm.php
> +    $form['profile_manager_url'] = [
Are you sure we can't "guess" this instead of asking the user to fill in this setting? I'll ask the team and get back to you on this.

2017-01-06 14:03 UTC, nickveenhof commented on src/Form/AdminSettingsForm.php
> +    $form['profile_manager_url'] = [
Also, we do not prevent them here from filling in the complete url. To reduce mistakes I'd really want us to remove this from the patch/module and fill it in automatically

2017-01-06 14:14 UTC, nickveenhof commented
Also I'd really like some Drupal 8 JS tests now that those are available before we get this in. See the facets module for examples on how that works.

2017-01-06 14:20 UTC, briancwald commented on assets/lift_inspector/acquia_lift_inspector.js
> +      $(document).keypress(function (e) {
Yes, I tested it in most browsers besides IE, but according to the docs, its supported.

2017-01-06 14:21 UTC, briancwald commented on src/Form/AdminSettingsForm.php
> +    $form['profile_manager_url'] = [
I agree, I would have much preferred to get that information directly from the JS but it is not available and this was the only method available to me. I didn't want that to stop me from making progress.

2017-01-06 14:22 UTC, briancwald commented on assets/lift_inspector/acquia_lift_inspector.js
> +        if (accountSubDomain) {
AFAICT, but we should ask Steve. In the case there is no prefix, I have accounted for that in the docs.

2017-01-11 10:45 UTC, closed without merging

2017-01-11 10:46 UTC, nickveenhof commented
Closing as duplicate of https://github.com/acquia/acquia_lift/pull/253. That PR is a refactored version