LEB-2661 | Create new 8.x-4.x Lift Drupal Module
acquia/acquia_lift pull request #281
Opened 2019-05-08 14:53 UTC by danikalmar

2019-05-09 13:07 UTC, scor requested changes

2019-05-09 13:07 UTC, scor commented on acquia_lift.install
> +  $advanced_settings := Drupal::configFactory()->getEditable('acquia_lift.settings')->get('advanced');
:= is Golang, not PHP ;)

2019-05-10 07:47 UTC, danikalmar commented on acquia_lift.install
> +  $advanced_settings := Drupal::configFactory()->getEditable('acquia_lift.settings')->get('advanced');
fixed

2019-05-10 13:26 UTC, danikalmar commented
duplicate PR, close it

2019-05-10 13:26 UTC, closed without merging