LCH-3698: Fix block content rendering.
acquia/acquia_lift pull request #291
Opened 2020-01-20 12:55 UTC by saxumVermes

2020-01-20 16:42 UTC, c0d39uru approved these changes

2020-02-14 16:28 UTC, c0d39uru approved these changes

2020-06-02 11:39 UTC, scor commented
Hi @saxumVermes, I wanted to merge your PR but looks like there are now some failures, not sure why they suddenly appeared since the tests were passing one month ago:
```
1) Drupal\Tests\acquia_lift_publisher\Kernel\EventSubscriber\EntityRenderHandlerTest::testImageAttributeIsSet
Error: Call to a member function getAttribute() on boolean
/home/travis/build/acquia/acquia_lift/modules/acquia_lift_publisher/tests/src/Kernel/EventSubscriber/Cdf/EntityRenderHandlerTest.php:202
--
1) Drupal\Tests\acquia_lift_publisher\Kernel\EventSubscriber\EntityRenderHandlerTest::testOnCreateCdfBlockContent
All entities were rendered.
Failed asserting that actual size 0 matches expected size 2.
/home/travis/build/acquia/acquia_lift/modules/acquia_lift_publisher/tests/src/Kernel/EventSubscriber/Cdf/EntityRenderHandlerTest.php:229
```

2020-06-02 14:58 UTC, scor requested changes

2020-06-02 14:58 UTC, scor commented on modules/acquia_lift_publisher/tests/src/Kernel/EventSubscriber/Cdf/EntityRenderHandlerTest.php
> + * Class EntityRenderHandlerTest.
we're missing a `@group acquia_lift` here.

2020-06-02 14:58 UTC, scor commented on modules/acquia_lift_publisher/tests/src/Kernel/EventSubscriber/Cdf/EntityRenderHandlerTest.php
> +namespace Drupal\Tests\acquia_lift_publisher\Kernel\EventSubscriber;
missing `\Cdf`, should read:
```
namespace Drupal\Tests\acquia_lift_publisher\Kernel\EventSubscriber\Cdf;
```

2020-06-02 15:37 UTC, scor commented
I've replayed all the changes that happened on the 4.x branch since you posted the inital PR (initially based on top of 8.x-4.1) and I've narrowed it down to #288... something in this other PR about Publish only required entities introduced something that is not compatible with this PR.

2020-06-03 17:39 UTC, scor approved these changes

2020-06-03 19:56 UTC, merged